name: CI Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      OPENRESTY_PREFIX: "/usr/local/openresty"

    services:
      etcd:
        image: bitnami/etcd:3.4.13
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: yes
          ETCD_ADVERTISE_CLIENT_URLS: 'http://0.0.0.0:2379'

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: main

      - name: Linux Get dependencies
        run: sudo apt install -y cpanminus build-essential libncurses5-dev libreadline-dev libssl-dev perl luarocks

      - name: Linux Before install
        run: |
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
          sudo luarocks install luacheck

      - name: Install openresty
        run: |
          wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
          sudo apt-get update
          sudo apt-get install openresty

      - name: Get apisix
        run: |
          git clone https://github.com/apache/apisix.git
          cd apisix
          make deps
          git submodule update --init --recursive
          make init

      - name: Linux Script
        run: |
          export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
          cd main
          make test
